spring:
    application:
        name: spring-boot-dotenv
    config:
        import: optional:file:.env[.properties]

    # h2 database
    h2:
        console:
            enabled: true
            path: /h2-console

    sql:
        init:
            mode: always
            schema-locations: classpath:init/h2.sql

    datasource:
        driver-class-name: org.h2.Driver
        url: jdbc:h2:mem:test
        username: sa
        password: 

    # datasource:
    #     url: jdbc:mysql://localhost:3306/mydb
    #     username: user
    #     password: pass
    #     driver-class-name: com.mysql.cj.jdbc.Driver

    # jpa:
    #     hibernate:
    #     ddl-auto: update
    #     show-sql: true
    #     properties:
    #     hibernate:
    #         format_sql: true

    thymeleaf:
        cache: false
        prefix: classpath:/templates/
        suffix: .html

    security:
        user:
            name: admin
            password: admin123
server:
    port: 8080


springdoc:
    packages-to-scan: com.sangsang.autoblog.adapter.in.web.controller
    default-consumes-media-type: application/json;charset=UTF-8
    default-produces-media-type: application/json;charset=UTF-8
    cache:
        disabled: true              # 캐시 사용 여부
    api-docs:
        path: /api-docs/json
        enabled: true
    swagger-ui:
        enabled: true               # Swagger UI 사용여부 : 접근 경로 => <http://localhost:8080/swagger-ui/index.html>
        path: /demo-ui.html         # Swagger UI 추가 접근 경로 => <http://localhost:8080/demo-ui.html>
        tags-sorter: alpha          # alpha: 알파벳 순 태그 정렬, method: HTTP Method 순 정렬
        operations-sorter: alpha    # alpha: 알파벳 순 태그 정렬, method: HTTP Method 순 정렬